### PR TITLE
If every antimatter were a planck volume... Time Dimensions EDIT

### PR DESCRIPTION
**Pull request by NewGitter2017**
Just added an extra pair of values to the scale1 and scale2 arrays to include Time Dimensions starting at 1e65000 antimatter

### CODE REVIEW

**Comment by aarextiaokhiao** [comment]
Reaching e95095 antimatter per meter was more balanced.

**Comment by NewGitter2017** [comment]
I'm a bit confused. Don't you get to eternity before 1e70000? I wasn't sure of the right value.

**Comment by aarextiaokhiao** [comment]
Was added

**Comment by omsi6** [comment]
This had been added, thanks for the suggestion.

**Pull request closed without merging**
