### PR TITLE
Achievement balancing 

### PR DESCRIPTION
**Pull request by pg132**

### CODE REVIEW

**Comment by aarextiaokhiao** [comment]
Are you seriously you want to turn the game?

**Comment by omsi6** [comment]
Is this just ng-- merged into the main game?

**Comment by dan-simon** [comment]
I'd assume it was an accidental pull request to the wrong place. Nyan cat never told me they wanted to try to merge NG-- into the main game, and I think it's the type of thing I'd have heard about.

**Comment by omsi6** [comment]
I'm going to assume dan-simon is correct here and just close this.

**Pull request closed without merging**
