### PR TITLE
Description.

### PR DESCRIPTION
**Pull request by NGCMan**
So people know what this is.

### CODE REVIEW

**Comment by YhvrWasTaken** [comment]
Maybe add a bit more? "After a certain point, you can 'Break Infinity', and pass larger numbers. After that, you can purchase infinity dimensions, which give a multiplier to all dimensions. After you have unlocked all 8 infinity dimensions, you can eternity, unlocking more upgrades, eternity milestones, and time dimensions, which boost your production even more" or something like that.

**Comment by EssJayEl** [comment]
Although that might be considered as spoilers by some people.

**Comment by NGCMan** [comment]
@EssJayEl is right, that's why I didn't add a lot of information.

**Comment by YhvrWasTaken** [comment]
Oh, ok.

**Comment by williamhatcher** [comment]
Why hasn't this or some other update to the README been committed?

**Comment by IvarK** [comment]
Updated the description to be accurate with the current state of the repo

**Pull request closed without merging**
